name: Deploy BDT Api to Azure App Service

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  IMAGE_NAME: bdt-api
  TAG: v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Autenticación en Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Iniciar sesión en Azure Container Registry
        run: |
          az acr login --name $AZURE_REGISTRY_NAME

      - name: Construir y subir la imagen Docker
        run: |
          docker buildx build --platform linux/amd64 -t $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG .
          docker push $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG

      - name: Configurar la imagen en App Service
        run: |
          az webapp config container set \
            --name $AZURE_WEBAPP_NAME \
            --resource-group my-resource-group \
            --docker-custom-image-name $AZURE_REGISTRY_NAME.azurecr.io/$IMAGE_NAME:$TAG \
            --docker-registry-server-url https://$AZURE_REGISTRY_NAME.azurecr.io

      - name: Reiniciar la aplicación
        run: |
          az webapp restart --name $AZURE_WEBAPP_NAME --resource-group my-resource-group
